name: 'Deploy PR to k8s'
description: 'deploys a pr branch to kubernetes using helm chart'
runs:
  using: docker
  image: Dockerfile
inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  prNumber:
    description: 'The number of the PR'
    required: false
  branchName:
    required: false
    description: 'pr branch name'
outputs:
  version:
    description: 'The new version to deploy'